### ISSUE TITLE
Can you please share the reasons for moving from RP2040 Chip to ESP32

### ISSUE THREAD

**Issue by codetiger** [DavidVentura/PicoPico#1]
Hi, 
This is a wonderful project and I would like to know more details about why you have abandoned the support for RP2040 chip. Some reasons I can think of are listed below. 

1. Lua overheads in calculations.
2. Memory limitations (If my understanding is correct, Pico-8 has only 64KB of memory addressing. If so why is it hard to fit in 264KB RAM that RP2040 has?)
3. Framerate issues?
4. Is the float point calculations slowing down? 

I am able to render 3D model with 5k triangles on to a 240x240 screen. using DMA and other features of the chip and it runs at 17 FPS. I am not loosing my hopes . :)

**Comment by DavidVentura** [comment]
Hi

I had the exact same idea initially; there's indeed 64KB of "machine memory" (with 32KB of scratch and 32KB affecting console state).. but there's also [this](https://pico-8.fandom.com/wiki/Memory#Lua_Memory) -- you can allocate up to **2MB** of Lua objects; ie: create a table with 20000 entries

Everything else can fit in memory, if barely, but the game-object memory won't.

The "abandoning" is a bit strong -- if you look at the `pico_backend.c` -- it is very small, at the moment the only thing missing from it is a way to play SFX, the rest works, so you can give it a shot

**Comment by codetiger** [comment]
I am thinking of a precompiled Lua code instead of real time interpreting. This should allow us to store the Lua memory 2mb in flash storage. Does it make sense?

**Comment by DavidVentura** [comment]
Pre-compiling would help a bit; it is in fact something I'm thinking about -- however you can always do this

```lua
function f()
        t = {}
        for var=1,100000 do
                t[var] = 5
        end     
end                    

f()

```

and it won't execute to completion on the Pico, there's no RAM to keep the table `t`

**Comment by DavidVentura** [comment]
Hey!
This does not currently work well, partly because it is incomplete and partly because I don't know enough about C++ to generate code properly, but I've started a Lua to C++ compiler here: https://github.com/DavidVentura/lua-but-worse
